### ISSUE TITLE
Exit does not work

### ISSUE THREAD

**Issue by Segelzwerg** [ink-inc/MagicMittelalterGame#187]
The exit button in the pause menu does not work in Linux. The exit in the main menu does work. Can't check other platforms.

**Comment by iTitus** [comment]
Did this get fixed by #209 ?
Can you test @Segelzwerg ?

**Comment by Segelzwerg** [comment]
I only works from the terrain scene and from the main menu.

It does not work in the test scene.

**Comment by iTitus** [comment]
strange
