### ISSUE TITLE
The Sound Areas break the raycast of the interactor

### ISSUE THREAD

**Issue by Thabb** [ink-inc/MagicMittelalterGame#234]
If you push any kind of interactable inside a music area its not possible to interact with it anymore from the outside.

**Comment by iTitus** [comment]
wut

**Comment by Segelzwerg** [comment]
http://answers.unity.com/answers/524444/view.html
It's old but maybe it's going to work.
However can't tell when I'll be able to fix it.

**Comment by Segelzwerg** [comment]
@Thabb Can you give instructions on how to reproduce?
