### ISSUE TITLE
Health / Armor getter

### ISSUE THREAD

**Issue by Segelzwerg** [ink-inc/MagicMittelalterGame#255]
Character needs health and armor getter.

This includes NPC and the player for both should use the same interface.

**Comment by iTitus** [comment]
This was done by #221 with the `AttributeHolder` class

**Comment by Segelzwerg** [comment]
I agree with you, but from my standpoint it would be nice to have an actual method called `GetHealth()` for all characters. So I reopen this, no offense intended.

To get into details. The AiWrapper should not guess how an attribute could be named, but simply call for every character (NPC & Player) this getter methods or properties.
